#include "bt_drv.h"
#include "drv.h"
void bt_initIO(void)
{
	GPIO_InitIO(BT_KEY_GPIO_PORT,BT_KEY_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(BT_LINK_STATE_GPIO_PORT,BT_LINK_STATE_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(GPIOA,GPIO_PIN_2,GPIO_MODE_AF_PP,GPIO_OSPEED_10MHZ);				//BT
	GPIO_InitIO(GPIOA,GPIO_PIN_3,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);	//BT	
		
}

