#include "ev1527_drv.h"
#include "drv.h"
void ev1527_initIO(void){
		GPIO_InitIO(EV1527_GPIO_PORT,EV1527_GPIO_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_50MHZ);
		// GPIO_InitIO(MODE_GPIO_PORT,MODE_GPIO_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_50MHZ);
		GPIO_InitIO(MODE_GPIO_PORT,MODE_GPIO_PIN,GPIO_MODE_IPU,GPIO_OSPEED_50MHZ);
		GPIO_InitIO(LED_GPIO_PORT,LED_GPIO_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ);
		GPIO_InitIO(WARMING_GPIO_PORT,WARMING_GPIO_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ);
}
