#include "gps_drv.h"
#include "drv.h"
void gps_initIO(void)
{
#if !HARD_TYPE_NEW	
	GPIO_InitIO(GPS_PWR_GPIO_PORT,GPS_PWR_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);

	GPIO_InitIO(GPS_RST_GPIO_PORT,GPS_RST_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);
#endif
	GPIO_InitIO(GPIOC,GPIO_PIN_10,GPIO_MODE_AF_PP,GPIO_OSPEED_10MHZ);				//GPS
	GPIO_InitIO(GPIOC,GPIO_PIN_11,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);	//GPS	
	
}

