#include "lcd_drv.h"
#include "drv.h"
void lcd_initIO(void)
{
	GPIO_InitIO(LCD_CS_GPIO_PORT,LCD_CS_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
	GPIO_InitIO(LCD_RST_GPIO_PORT,LCD_RST_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
	GPIO_InitIO(LCD_RS_GPIO_PORT,LCD_RS_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
	GPIO_InitIO(LCD_CLK_GPIO_PORT,LCD_CLK_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
	GPIO_InitIO(LCD_DAT_GPIO_PORT,LCD_DAT_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
//	GPIO_InitIO(LCD_ROM_IN_GPIO_PORT,LCD_ROM_IN_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);	
//	GPIO_InitIO(LCD_ROM_OUT_GPIO_PORT,LCD_ROM_OUT_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
//	GPIO_InitIO(LCD_ROM_CLK_GPIO_PORT,LCD_ROM_CLK_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	
//	GPIO_InitIO(LCD_ROM_CS_GPIO_PORT,LCD_ROM_CS_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);			
	GPIO_InitIO(LCD_LCON_GPIO_PORT,LCD_LCON_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_10MHZ);	

	LCD_CLK_OFF();
	LCD_DAT_OFF();
	LCD_RS_OFF();
	LCD_RST_OFF();
	LCD_CS_OFF();

	LCON_ON();

}

void lcd_initIO_PwrOff(void)
{
	LCD_CLK_OFF();
	LCD_DAT_OFF();
	LCD_RS_OFF();
	LCD_RST_OFF();
	LCD_CS_OFF();
	LCON_OFF();	
	
	GPIO_InitIO(LCD_CS_GPIO_PORT,LCD_CS_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);

	GPIO_InitIO(LCD_RST_GPIO_PORT,LCD_RST_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(LCD_RS_GPIO_PORT,LCD_RS_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(LCD_CLK_GPIO_PORT,LCD_CLK_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(LCD_DAT_GPIO_PORT,LCD_DAT_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(LCD_LCON_GPIO_PORT,LCD_LCON_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	

}

