#include "led_drv.h"
#include "drv.h"


void led_initIO(void)
{
	#if USING_LED_DMA_SEND

    rcu_periph_clock_enable(RCU_GPIOB);
    rcu_periph_clock_enable(RCU_AF);

	GPIO_InitIO(LED_DATA_GPIO_PORT,LED_DATA_GPIO_PIN,GPIO_MODE_AF_PP,GPIO_OSPEED_50MHZ);
	
	GPIO_InitIO(LED_RCK_GPIO_PORT,LED_RCK_GPIO_PIN,GPIO_MODE_AF_PP,GPIO_OSPEED_50MHZ);

	GPIO_InitIO(LED_SCK_GPIO_PORT,LED_SCK_GPIO_PIN,GPIO_MODE_AF_PP,GPIO_OSPEED_50MHZ);


	#else
	GPIO_InitIO(LED_DATA_GPIO_PORT,LED_DATA_GPIO_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ);
	
	GPIO_InitIO(LED_RCK_GPIO_PORT,LED_RCK_GPIO_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ);

	GPIO_InitIO(LED_SCK_GPIO_PORT,LED_SCK_GPIO_PIN,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ);

	gpio_bit_reset(LED_DATA_GPIO_PORT,LED_DATA_GPIO_PIN);
	gpio_bit_reset(LED_RCK_GPIO_PORT,LED_RCK_GPIO_PIN);
	gpio_bit_reset(LED_SCK_GPIO_PORT,LED_SCK_GPIO_PIN);
	#endif
}

