#include "music_drv.h"
#include "drv.h"
void music_initIO(void)
{
	GPIO_InitIO(MUSIC_BUSY_GPIO_PORT,MUSIC_BUSY_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	
	GPIO_InitIO(GPIOC,GPIO_PIN_12,GPIO_MODE_AF_PP,GPIO_OSPEED_10MHZ);				//MUSIC
	GPIO_InitIO(GPIOD,GPIO_PIN_2,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);	//MUSIC
		
}

