#include "rf_315m_drv.h"
#include "drv.h"
void rf_315m_initIO(void)
{
	GPIO_InitIO(RF_D0_GPIO_PORT,RF_D0_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);

	GPIO_InitIO(RF_D1_GPIO_PORT,RF_D1_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);

	GPIO_InitIO(RF_D2_GPIO_PORT,RF_D2_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);

	GPIO_InitIO(RF_D3_GPIO_PORT,RF_D3_PIN,GPIO_MODE_IN_FLOATING,GPIO_OSPEED_10MHZ);
	

}

